export const teamSchema = {
  id: "string",
  name: "string",
  type: "mountain|water|urban|forest|air|search",
  status: "available|standby|tasked",
  etaMinutes: "number",
  region: "string",
  area: "string",
  location: {
    label: "string",
    latitude: "number",
    longitude: "number",
  },
  people: "number",
  capabilities: [
    "steep-ground",
    "rope-rescue",
    "medical",
    "night-operations",
    "search",
    "off-road",
    "swift-water",
    "winch",
    "aerial-search",
  ],
  equipment: ["string"],
  jurisdiction: "string",
  contact: "string",
  notes: "string",
};

export const teams = [
  {
    id: "ridge-1",
    name: "Ridge 1",
    type: "mountain",
    status: "available",
    etaMinutes: 24,
    region: "North County",
    area: "North Ridge / High Fell",
    location: { label: "Keswick", latitude: 54.6013, longitude: -3.1347 },
    people: 6,
    capabilities: [
      "steep-ground",
      "rope-rescue",
      "medical",
      "night-operations",
    ],
    equipment: ["technical rope kit", "thermal camera", "vacuum mattress"],
    jurisdiction: "North County SAR Unit",
    contact: "Ops Channel 2",
    notes: "Primary response for cliff and high-altitude incidents.",
  },
  {
    id: "valley-3",
    name: "Valley 3",
    type: "search",
    status: "available",
    etaMinutes: 14,
    region: "East Valley",
    area: "Lower Valley / East Trail",
    location: { label: "York", latitude: 53.959, longitude: -1.0815 },
    people: 4,
    capabilities: ["search", "medical", "off-road"],
    equipment: ["4×4 response vehicle", "first response kit", "drone"],
    jurisdiction: "East Valley Fire & Rescue",
    contact: "Alpha Dispatch",
    notes:
      "Fastest local responder for terrain searches and lost-person incidents.",
  },
  {
    id: "swift-water-2",
    name: "Swift Water 2",
    type: "water",
    status: "tasked",
    etaMinutes: 38,
    region: "River District",
    area: "River District / Canyon Run",
    location: { label: "Shrewsbury", latitude: 52.7073, longitude: -2.7553 },
    people: 5,
    capabilities: ["swift-water", "medical", "night-operations"],
    equipment: ["inflatable rescue boat", "dry suits", "throw lines"],
    jurisdiction: "River District Authority",
    contact: "Water Ops",
    notes: "Assigned to a concurrent flood and vehicle recovery callout.",
  },
  {
    id: "air-support",
    name: "Air Support",
    type: "air",
    status: "standby",
    etaMinutes: 31,
    region: "Regional",
    area: "Regional Air Corridor",
    location: { label: "Leeds", latitude: 53.8008, longitude: -1.5491 },
    people: 3,
    capabilities: ["winch", "aerial-search", "medical", "night-operations"],
    equipment: ["winch", "night vision", "stretcher"],
    jurisdiction: "Regional Aviation Unit",
    contact: "Air Desk",
    notes:
      "Available for rapid visual search and extraction when weather permits.",
  },
  {
    id: "forest-4",
    name: "Forest 4",
    type: "forest",
    status: "available",
    etaMinutes: 19,
    region: "West Forest",
    area: "Black Pine / Old Logging Road",
    location: { label: "Brecon", latitude: 51.9468, longitude: -3.3909 },
    people: 7,
    capabilities: ["search", "off-road", "steep-ground", "medical"],
    equipment: ["tracked utility vehicle", "chainsaw", "shelter kit"],
    jurisdiction: "West Forest Ranger Service",
    contact: "Forest Dispatch",
    notes:
      "Strong for dense woodland searches and remote extraction logistics.",
  },
  {
    id: "harbor-5",
    name: "Harbor 5",
    type: "water",
    status: "standby",
    etaMinutes: 27,
    region: "Coastal Belt",
    area: "Harbor Mouth / Jetty Walk",
    location: { label: "Dover", latitude: 51.1279, longitude: 1.3134 },
    people: 5,
    capabilities: ["swift-water", "medical", "search"],
    equipment: ["rescue sled", "throw bags", "marine radio"],
    jurisdiction: "Coastal Rescue Board",
    contact: "Harbor Control",
    notes: "Best suited to surf, estuary, and shoreline emergencies.",
  },
  {
    id: "cave-6",
    name: "Cave 6",
    type: "search",
    status: "available",
    etaMinutes: 46,
    region: "Southern Range",
    area: "Karst Caverns / Sinkholes",
    location: { label: "Mendip Hills", latitude: 51.255, longitude: -2.712 },
    people: 6,
    capabilities: ["rope-rescue", "search", "medical"],
    equipment: ["cave rescue kit", "gas monitors", "anchor hardware"],
    jurisdiction: "Southern Region SAR Team",
    contact: "Cave Desk",
    notes: "Specialized in confined-space and subterranean rescues.",
  },
  {
    id: "urban-7",
    name: "Urban 7",
    type: "urban",
    status: "available",
    etaMinutes: 12,
    region: "City Metro",
    area: "Downtown / Metro Tunnels",
    location: { label: "Birmingham", latitude: 52.4862, longitude: -1.8904 },
    people: 8,
    capabilities: ["medical", "search", "off-road"],
    equipment: ["hydraulic cutters", "high-angle gear", "thermal imager"],
    jurisdiction: "Metro Urban Rescue",
    contact: "Metro Command",
    notes: "High-density urban response with structural and tunnel expertise.",
  },
  {
    id: "summit-8",
    name: "Summit 8",
    type: "mountain",
    status: "tasked",
    etaMinutes: 52,
    region: "Northern Peaks",
    area: "Snowcap Ridge / Glacier Face",
    location: { label: "Aviemore", latitude: 57.189, longitude: -3.8292 },
    people: 9,
    capabilities: [
      "steep-ground",
      "rope-rescue",
      "night-operations",
      "medical",
    ],
    equipment: ["snow anchors", "alpine stretcher", "avalanche beacon"],
    jurisdiction: "Highland Authority",
    contact: "Summit Coordination",
    notes: "Heavy alpine team handling winter and glacier incidents.",
  },
  {
    id: "trail-9",
    name: "Trail 9",
    type: "search",
    status: "standby",
    etaMinutes: 22,
    region: "Central Lakes",
    area: "Lake Loop / East Fork",
    location: { label: "Peak District", latitude: 53.349, longitude: -1.77 },
    people: 5,
    capabilities: ["search", "off-road", "medical"],
    equipment: ["trail bikes", "camping kits", "portable radio"],
    jurisdiction: "Central Lakes Ranger Unit",
    contact: "Lake Control",
    notes:
      "Primarily used for hikers, trail accidents, and remote evacuations.",
  },
  {
    id: "delta-10",
    name: "Delta 10",
    type: "water",
    status: "available",
    etaMinutes: 29,
    region: "South Delta",
    area: "South Marsh / Floodplain",
    location: { label: "The Wash", latitude: 52.93, longitude: 0.3 },
    people: 6,
    capabilities: ["swift-water", "search", "medical"],
    equipment: ["rescue skiff", "flood barriers", "throw rope"],
    jurisdiction: "South Delta Infrastructure",
    contact: "Flood Desk",
    notes: "Handles waterlogged lowlands, flood channels, and marsh rescues.",
  },
  {
    id: "peak-11",
    name: "Peak 11",
    type: "mountain",
    status: "available",
    etaMinutes: 34,
    region: "Western Escarpment",
    area: "Granite Spur / Scree Slope",
    location: { label: "Eryri", latitude: 53.0685, longitude: -4.0763 },
    people: 5,
    capabilities: ["steep-ground", "rope-rescue", "off-road"],
    equipment: ["mountain rescue packs", "sling systems", "helmet lights"],
    jurisdiction: "Western Escarpment Rescue",
    contact: "Escarpment Ops",
    notes: "Strong for rockfall, scree, and steep terrain recovery.",
  },
  {
    id: "night-12",
    name: "Night 12",
    type: "search",
    status: "available",
    etaMinutes: 18,
    region: "North City",
    area: "North City Greenbelt",
    location: { label: "Newcastle", latitude: 54.9783, longitude: -1.6178 },
    people: 4,
    capabilities: ["night-operations", "search", "medical"],
    equipment: ["night optics", "portable flood lights", "med packs"],
    jurisdiction: "North City Fire Service",
    contact: "Nightwatch",
    notes:
      "Focused on darkness operations and late-hour missing-person searches.",
  },
  {
    id: "storm-13",
    name: "Storm 13",
    type: "air",
    status: "standby",
    etaMinutes: 41,
    region: "Regional",
    area: "Storm Corridor / Ridge Lines",
    location: { label: "Glasgow", latitude: 55.8642, longitude: -4.2518 },
    people: 3,
    capabilities: ["aerial-search", "medical", "night-operations"],
    equipment: ["rotorcraft kit", "forward-looking radar", "med sling"],
    jurisdiction: "Regional Emergency Aviation",
    contact: "Weather Desk",
    notes: "Used during severe-weather reconnaissance and extraction windows.",
  },
  {
    id: "quarry-14",
    name: "Quarry 14",
    type: "urban",
    status: "tasked",
    etaMinutes: 36,
    region: "Industrial Belt",
    area: "Quarry Works / East Cut",
    location: { label: "Milton Keynes", latitude: 52.0406, longitude: -0.7594 },
    people: 7,
    capabilities: ["search", "medical", "steep-ground"],
    equipment: ["excavation support", "lifting harnesses", "portable lighting"],
    jurisdiction: "Industrial Safety Unit",
    contact: "Works Ops",
    notes:
      "Specialized in industrial sites, abandoned pits, and heavy equipment incidents.",
  },
  {
    id: "ridge-15",
    name: "Ridge 15",
    type: "mountain",
    status: "available",
    etaMinutes: 26,
    region: "High Country",
    area: "Moraine Pass / Ice Shelf",
    location: { label: "Fort William", latitude: 56.8198, longitude: -5.1052 },
    people: 6,
    capabilities: [
      "steep-ground",
      "rope-rescue",
      "medical",
      "night-operations",
    ],
    equipment: ["ice screws", "crampons", "cold-weather bivvy"],
    jurisdiction: "High Country Patrol",
    contact: "Ridge Desk",
    notes:
      "High-country mountain response with cold-weather rescue capability.",
  },
  {
    id: "marsh-16",
    name: "Marsh 16",
    type: "water",
    status: "available",
    etaMinutes: 33,
    region: "East Wetlands",
    area: "Reed Basin / Canal Line",
    location: { label: "Norfolk Broads", latitude: 52.61, longitude: 1.5 },
    people: 5,
    capabilities: ["swift-water", "search", "off-road"],
    equipment: ["wading gear", "rescue raft", "cable puller"],
    jurisdiction: "Wetland Response Group",
    contact: "Canal Desk",
    notes: "Handles soft-ground water incidents and canal-side recoveries.",
  },
  {
    id: "fox-17",
    name: "Fox 17",
    type: "forest",
    status: "available",
    etaMinutes: 21,
    region: "South Pine",
    area: "South Pine / Creek Valley",
    location: { label: "New Forest", latitude: 50.87, longitude: -1.58 },
    people: 6,
    capabilities: ["search", "steep-ground", "medical"],
    equipment: ["trail support packs", "tracking boards", "first aid cache"],
    jurisdiction: "South Pine Volunteer SAR",
    contact: "Pine Dispatch",
    notes: "Good for rugged woodland and creekside support operations.",
  },
  {
    id: "bluff-18",
    name: "Bluff 18",
    type: "search",
    status: "standby",
    etaMinutes: 17,
    region: "Coastal Cliffs",
    area: "Bluff Path / Sea Stack",
    location: { label: "Pembrokeshire", latitude: 51.7, longitude: -5.0 },
    people: 4,
    capabilities: ["search", "medical", "off-road"],
    equipment: ["portable beacon", "stretcher sled", "coastal radio"],
    jurisdiction: "Coastal Cliffs Unit",
    contact: "Cliff Desk",
    notes:
      "Fast coastal access team for bluffs, cliffs, and shoreline recoveries.",
  },
  {
    id: "rescue-19",
    name: "Rescue 19",
    type: "urban",
    status: "available",
    etaMinutes: 15,
    region: "City North",
    area: "Rail Yard / Bridge Span",
    location: { label: "Manchester", latitude: 53.4808, longitude: -2.2426 },
    people: 8,
    capabilities: ["medical", "search", "rope-rescue"],
    equipment: ["bridge rescue kit", "cutting tools", "stretcher baskets"],
    jurisdiction: "North Rail Safety Network",
    contact: "Rail Ops",
    notes:
      "Specialist team for bridge, rail, and elevated structure incidents.",
  },
  {
    id: "glacier-20",
    name: "Glacier 20",
    type: "mountain",
    status: "tasked",
    etaMinutes: 49,
    region: "Frost Range",
    area: "Frost Range / Icefall",
    location: { label: "Glencoe", latitude: 56.6826, longitude: -5.1023 },
    people: 7,
    capabilities: [
      "steep-ground",
      "rope-rescue",
      "medical",
      "night-operations",
    ],
    equipment: ["ice rescue sled", "glacier anchors", "thermal gear"],
    jurisdiction: "Frost Range Authority",
    contact: "Ice Desk",
    notes: "Prepared for icefall, crevasse, and glacier extraction events.",
  },
];
